name: DJ Mike Moovz
favicon: null
layout_spectrum: 0.24572252132929862
typography_spectrum: 0.1634286311455071
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#443674'
    - '#ff911a'
    - '#0076fb'
  brandStrength: 0.27198294876143336
  lightness: 0.8019250403158367
  saturation: 0.38458247249946
  rhythmicContrast: 0.4211516201030463
purpose: []
